### ISSUE TITLE
Use Travis to build and add the javascript files to the project for every push.

### ISSUE THREAD

**Issue by Scoombe** [Scoombe/wpmTest#36]
Needs to build the java script and update it to the project.

**Comment by fabrv** [comment]
I can help you with this but you'll need give me some permissions to your repository or create a GIT_TOKEN and share it with me.
Although I can help you I highly recommend against it for this reasons:
* Sharing the GIT_TOKEN is not recommended.
* Build files should not be committed.
* Travis should probably not be used to do this.

My personal recommendations:
* Do not commit build files, add the next line to the .gitignore
  * `\bin\`
* Use Travis for testing, not for building
  * Obviously building could be a step in the test and you might want to do something with the built  but instead of pushing it to the master branch create a new branch use by travis where it pushes the changes.

If you despite my recommendations still want to push the built code I can still help you.

**Comment by Scoombe** [comment]
The point is so that the js can be deployed to npm. I can add the encrypted git token using the travis CLI. 
It would be saving people having to check in the changes from the build when it can be generated by travis.

**Comment by Scoombe** [comment]
Having looked at the travis build erroring after the changes. I think I should have just followed your advice and not push the changes back to github. Thanks for your changes! I have now just fixed the npm publishing through travis.
